@startuml

object Note{
title
}

object NoteAudio{
fileLenght
filePath
}

object NoteImage{
file
}

object NoteText{
body
}

object audioCreatorActivity{
LOG_TAG
REQUEST_RECORD_AUDIO_PERMISSION
filePath
fileLenght
mRecorder
recordButton
mStartRecording
nChronometer
viewModel
}

object audioViewActivity{
LOG_TAG
viewModel
mMediaPlayer
mHandler
isPlaying
filePath
playBtn
mSeekBar
minutes
seconds
actualTimerTextView
fileLenghtTextView
}

object CarteraUsuari{
userList
}

object imageCreatorActivity{
selectedImage
camera_button
gallery_button
imageUri
viewModel
GALLERY_REQUEST_CODE
GALLERY_PERMISSION_CODE
CAMERA_PERMISSION_CODE
CAMERA_REQUEST_CODE
}

object imageViewActivity{
viewModel
}

object LoginActivity{
viewModel
}

object MainActivity{
noteListAdapter
viewModel
}

object NoteListAdapter{
noteList
lInflater
context
mOnNoteListener
}

object SharedViewModel{
loggedInUser
noteList
userList
noteToView
TAG
}

object SignUpActivity{
viewModel
}

object textCreatorActivity{
viewModel
}

object textViewActivity{
viewModel
}

object User{
userName
password
noteList
}


CarteraUsuari "1" *-- "1, ,*" User : té
User "1" -- "0, ,100" Note: té

Note <|-- NoteText
Note <|-- NoteAudio
Note <|-- NoteImage


MainActivity "*" *-- "1" SharedViewModel : té

SharedViewModel "1" *-- "1" NoteListAdapter : té
SharedViewModel "1" *--- "1" CarteraUsuari : té
NoteListAdapter "1" *---- "0, ,100" Note : té

SharedViewModel "1" -- "*" imageCreatorActivity : té
SharedViewModel "1" -- "*" audioCreatorActivity : té
SharedViewModel "1" -- "*" textCreatorActivity : té

SharedViewModel "1" -- "*" imageViewActivity : té
SharedViewModel "1" -- "*" audioViewActivity : té
SharedViewModel "1" -- "*" textViewActivity : té

SharedViewModel "1" -- "*" LoginActivity : té
SharedViewModel "1" -- "*" SignUpActivity : té

MainActivity "1" ---- "*" audioCreatorActivity: navega
MainActivity "1" ---- "*" imageCreatorActivity: navega
MainActivity "1" ---- "*" textCreatorActivity: navega

MainActivity "1" ---- "*" audioViewActivity: navega
MainActivity "1" ---- "*" imageViewActivity: navega
MainActivity "1" ---- "*" textViewActivity: navega




@enduml