@startuml
object MainActivity{
noteListAdapter
veiwModel
}

object CarteraUsuari{
userList
}

object Usuari{
userName
password
noteList
}

object imageCreatorActivity{
selectedImage
camera_button
gallery_button
imageUri
viewModel
}

object textCreatorActivity{
viewModel
}

object audioCreatorActivity{
viewModel
}

object imageViewActivity{
viewModel
}

object textViewActivity{
viewModel
}

object audioViewActivity{
viewModel
}

object SignUpActivity{
viewModel
}

object LoginActivity{
viewModel
}

object SharedViewModel{
loggedInUser
noteList
userList
noteToView
TAG
}

object NoteListAdapter{
noteList
lInflater
mOnNoteListener
}

object Note{
title
}

object NoteAudio{

}

object NoteImage{
file
}

object NoteText{
body
}

CarteraUsuari "1" *-- "1, ,*" Usuari : té
Usuari "1" -- "0, ,100" Note: té

Note <|-- NoteText
Note <|-- NoteAudio
Note <|-- NoteImage


MainActivity "1" *-- "1" SharedViewModel : té
SharedViewModel "1" *-- "1" NoteListAdapter : té
SharedViewModel "1" *--- "1" CarteraUsuari : té
NoteListAdapter "1" *---- "0, ,100" Note : té

SharedViewModel "1" -- "1" imageCreatorActivity
SharedViewModel "1" -- "1" audioCreatorActivity
SharedViewModel "1" -- "1" textCreatorActivity

SharedViewModel "1" -- "1" imageViewActivity
SharedViewModel "1" -- "1" audioViewActivity
SharedViewModel "1" -- "1" textViewActivity

SharedViewModel "1" -- "1" LoginActivity
SharedViewModel "1" -- "1" SignUpActivity


@enduml